spring:
  application:
    name: backend
  main:
    banner-mode: "off"
  config:
    import: env.yaml
  datasource:
    url: jdbc:postgresql://${DB.HOST}:${DB.PORT}/${DB.NAME}
    username: ${DB.USERNAME}
    password: ${DB.PASSWORD}
    platform: postgres
    initialization-mode: always
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org:
      springframework:
        orm: debug


